# Generated by Django 2.1.3 on 2018-11-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0005_auto_20181129_2021'),
        ('apile_app', '0004_comment'),
    ]

    operations = [
    ]
