# Generated by Django 2.1.3 on 2018-11-30 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apile_app', '0006_merge_20181130_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voted_posts',
            field=models.ManyToManyField(related_name='voted_posts', through='apile_app.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('post', 'author')},
        ),
    ]
