# Generated by Django 2.1.3 on 2018-12-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0007_auto_20181130_1454'),
        ('apile_app', '0006_merge_20181130_1322'),
    ]

    operations = [
    ]
