# Generated by Django 2.0 on 2018-12-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0008_merge_20181201_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
