# Generated by Django 2.0 on 2018-12-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0009_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
