# Generated by Django 2.0 on 2018-12-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0014_auto_20181202_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
