# Generated by Django 2.0 on 2018-12-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0016_auto_20181202_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
