# Generated by Django 2.0 on 2018-12-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0018_auto_20181202_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
