# Generated by Django 2.0 on 2018-12-03 00:33

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0019_auto_20181202_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=10, populate_from=('description',), unique=True, verbose_name='slug'),
        ),
    ]
