# Generated by Django 2.0 on 2018-12-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0009_auto_20181202_1725'),
        ('apile_app', '0021_auto_20181202_2152'),
    ]

    operations = [
    ]
