# Generated by Django 2.1.3 on 2018-11-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0003_merge_20181127_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
