# Generated by Django 2.1.3 on 2018-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apile_app', '0004_post_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
